apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: hirex
type: Opaque
stringData:
  POSTGRES_DB: hirexdb
  POSTGRES_USER: hirex
  POSTGRES_PASSWORD: hirex_dev_pass
  DATABASE_URL: postgresql://hirex:hirex_dev_pass@postgres-svc:5432/hirexdb
